"""initial22

Revision ID: 998fdfd4d03b
Revises: 0925bb65cfec
Create Date: 2024-06-08 15:06:47.830548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998fdfd4d03b'
down_revision: Union[str, None] = '0925bb65cfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_project', sa.String(), nullable=False),
    sa.Column('Size_apartment', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Images', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIO', sa.String(), nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.Column('Size_apartment', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
